### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by aeroechelon** [goncalossilva/alfred2-android_sdk_reference_search-workflow#1]
![image](https://cloud.githubusercontent.com/assets/2360095/12875491/bf4d27b2-cdb9-11e5-9ca9-0ebe9a6d986e.png)

As soon as I enter a search term I do see 'Loading Android SDK reference data' but then it falls back to Alfred fallback.

On Alfred v2.8.2

**Comment by goncalossilva** [comment]
Hi! Unfortunately I'm not using Alfred anymore (or this extension), but I'll gladly accept any pull requests!

**Comment by aeroechelon** [comment]
Looking at the logs, the error is:

```
`scan': invalid byte sequence in US-ASCII (ArgumentError)
```

**Comment by aeroechelon** [comment]
See #2 for fix!
